# Generated by Django 5.2.17 on 2026-08-24 18:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("alumnos", "0001_initial"),
        ("instituciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoCobro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=140)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo_general",
                    models.CharField(
                        choices=[
                            ("INSCRIPCION", "Inscripción"),
                            ("MENSUALIDAD", "Mensualidad"),
                            ("EXTRAORDINARIO", "Extraordinario"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                (
                    "monto_predeterminado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("activo", models.BooleanField(default=True)),
                ("recurrente", models.BooleanField(default=False)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conceptos_cobro",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=220)),
                ("fecha_emision", models.DateField()),
                ("fecha_vencimiento", models.DateField()),
                (
                    "monto_original",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("motivo_descuento", models.CharField(blank=True, max_length=220)),
                (
                    "recargo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIAL", "Parcial"),
                            ("PAGADO", "Pagado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=80)),
                ("periodo_referencia", models.CharField(blank=True, max_length=7)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="descuentos_autorizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "familia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargos",
                        to="alumnos.familia",
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="alumnos.inscripcion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="finanzas.conceptocobro",
                    ),
                ),
            ],
            options={
                "ordering": ("fecha_vencimiento", "alumno__primer_apellido"),
            },
        ),
        migrations.CreateModel(
            name="ConfiguracionFinanciera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("moneda", models.CharField(default="GTQ", max_length=3)),
                ("simbolo_moneda", models.CharField(default="Q", max_length=5)),
                (
                    "dia_vencimiento_mensualidad",
                    models.PositiveSmallIntegerField(default=10),
                ),
                ("aplicar_mora", models.BooleanField(default=False)),
                (
                    "monto_mora_predeterminado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("permitir_pago_mayor_saldo", models.BooleanField(default=False)),
                ("numeracion_recibos", models.PositiveBigIntegerField(default=0)),
                ("prefijo_recibo", models.CharField(default="REC", max_length=20)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "institucion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_financiera",
                        to="instituciones.institucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=30)),
                ("nombre", models.CharField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metodos_pago",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateTimeField(default=django.utils.timezone.now)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("referencia", models.CharField(blank=True, max_length=120)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CONFIRMADO", "Confirmado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                    ),
                ),
                ("recibo_numero", models.CharField(blank=True, max_length=50)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "anulado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_anulados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "familia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="alumnos.familia",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "metodo_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="finanzas.metodopago",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_pago",),
            },
        ),
        migrations.CreateModel(
            name="AplicacionPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto_aplicado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aplicaciones_pago",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aplicaciones",
                        to="finanzas.cargo",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="aplicaciones",
                        to="finanzas.pago",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="conceptocobro",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="concepto_cobro_codigo_unico"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["institucion", "fecha_emision"], name="cargo_inst_emision_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["institucion", "fecha_vencimiento"], name="cargo_inst_vence_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["institucion", "concepto"], name="cargo_inst_concepto_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["alumno", "estado"], name="cargo_alumno_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["familia", "estado"], name="cargo_familia_estado_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cargo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("periodo_referencia", ""), _negated=True),
                fields=("institucion", "alumno", "concepto", "periodo_referencia"),
                name="cargo_recurrente_unico_alumno",
            ),
        ),
        migrations.AddConstraint(
            model_name="metodopago",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="metodo_pago_codigo_unico"
            ),
        ),
        migrations.AddIndex(
            model_name="pago",
            index=models.Index(
                fields=["institucion", "fecha_pago"], name="pago_inst_fecha_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="pago",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recibo_numero", ""), _negated=True),
                fields=("institucion", "recibo_numero"),
                name="recibo_unico_institucion",
            ),
        ),
        migrations.AddConstraint(
            model_name="aplicacionpago",
            constraint=models.UniqueConstraint(
                fields=("pago", "cargo"), name="aplicacion_unica_pago_cargo"
            ),
        ),
    ]
