import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations,models
class Migration(migrations.Migration):
 initial=True
 dependencies=[("academico","0001_initial"),("instituciones","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name="Docente",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("codigo",models.CharField(blank=True,max_length=20,null=True)),("cui",models.CharField(blank=True,max_length=13,null=True,validators=[django.core.validators.RegexValidator("^\\d{13}$","El CUI debe contener exactamente 13 dígitos.")])),("primer_nombre",models.CharField(max_length=60)),("segundo_nombre",models.CharField(blank=True,max_length=60)),("otros_nombres",models.CharField(blank=True,max_length=100)),("primer_apellido",models.CharField(max_length=60)),("segundo_apellido",models.CharField(blank=True,max_length=60)),("fecha_nacimiento",models.DateField(blank=True,null=True)),("sexo",models.CharField(blank=True,choices=[("F","Femenino"),("M","Masculino"),("O","Otro / no especificado")],max_length=1)),("telefono",models.CharField(max_length=30)),("email",models.EmailField(blank=True,max_length=254)),("direccion",models.TextField(blank=True)),("titulo_profesional",models.CharField(blank=True,max_length=180)),("especialidad",models.CharField(blank=True,max_length=160)),("fotografia",models.ImageField(blank=True,upload_to="docentes/fotografias/",validators=[django.core.validators.FileExtensionValidator(["jpg","jpeg","png","webp"])])),("fecha_ingreso",models.DateField()),("estado",models.CharField(choices=[("ACTIVO","Activo"),("INACTIVO","Inactivo"),("SUSPENDIDO","Suspendido"),("RETIRADO","Retirado")],default="ACTIVO",max_length=12)),("observaciones",models.TextField(blank=True)),("fecha_creacion",models.DateTimeField(auto_now_add=True)),("fecha_actualizacion",models.DateTimeField(auto_now=True)),("institucion",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="docentes",to="instituciones.institucion")),("usuario",models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="expediente_docente",to=settings.AUTH_USER_MODEL))],options={"ordering":("primer_apellido","segundo_apellido","primer_nombre")}),
  migrations.CreateModel(name="AsignacionDocente",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("fecha_inicio",models.DateField()),("fecha_fin",models.DateField(blank=True,null=True)),("activa",models.BooleanField(default=True)),("es_titular",models.BooleanField(default=True)),("observaciones",models.TextField(blank=True)),("fecha_creacion",models.DateTimeField(auto_now_add=True)),("fecha_actualizacion",models.DateTimeField(auto_now=True)),("ciclo",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="asignaciones_docentes",to="academico.cicloescolar")),("curso",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="asignaciones_docentes",to="academico.cursoinstitucion")),("docente",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="asignaciones",to="docentes.docente")),("grado",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="asignaciones_docentes",to="academico.gradoinstitucion")),("institucion",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="asignaciones_docentes",to="instituciones.institucion")),("oferta_academica",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="asignaciones_docentes",to="academico.ofertaacademica")),("seccion",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="asignaciones_docentes",to="academico.seccion"))],options={"ordering":("ciclo__anio","seccion__nombre","curso__orden")}),
  migrations.CreateModel(name="AsignacionGuia",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("fecha_inicio",models.DateField()),("fecha_fin",models.DateField(blank=True,null=True)),("activa",models.BooleanField(default=True)),("fecha_creacion",models.DateTimeField(auto_now_add=True)),("ciclo",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="asignaciones_guia",to="academico.cicloescolar")),("docente",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="secciones_guia",to="docentes.docente")),("institucion",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="asignaciones_guia",to="instituciones.institucion")),("seccion",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="asignaciones_guia",to="academico.seccion"))],options={"ordering":("-ciclo__anio","seccion__nombre")}),
  migrations.AddConstraint(model_name="docente",constraint=models.UniqueConstraint(condition=models.Q(("codigo__isnull",False)),fields=("institucion","codigo"),name="docente_codigo_unico_inst")),migrations.AddConstraint(model_name="docente",constraint=models.UniqueConstraint(condition=models.Q(("cui__isnull",False)),fields=("institucion","cui"),name="docente_cui_unico_inst")),migrations.AddIndex(model_name="docente",index=models.Index(fields=["institucion","estado"],name="docente_inst_estado_idx")),migrations.AddIndex(model_name="docente",index=models.Index(fields=["institucion","primer_apellido","primer_nombre"],name="docente_nombre_idx")),
  migrations.AddConstraint(model_name="asignaciondocente",constraint=models.UniqueConstraint(condition=models.Q(("activa",True)),fields=("docente","ciclo","seccion","curso"),name="asignacion_docente_activa_unica")),migrations.AddConstraint(model_name="asignaciondocente",constraint=models.UniqueConstraint(condition=models.Q(("activa",True),("es_titular",True)),fields=("ciclo","seccion","curso"),name="titular_unico_curso_seccion")),migrations.AddIndex(model_name="asignaciondocente",index=models.Index(fields=["institucion","ciclo","activa"],name="asig_doc_inst_ciclo_idx")),
  migrations.AddConstraint(model_name="asignacionguia",constraint=models.UniqueConstraint(condition=models.Q(("activa",True)),fields=("ciclo","seccion"),name="guia_activo_unico_seccion")),migrations.AddIndex(model_name="asignacionguia",index=models.Index(fields=["institucion","ciclo","activa"],name="guia_inst_ciclo_idx")),
 ]
