# Generated by Django 5.2.17 on 2026-08-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventoauditoria",
            name="detalles",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
