# Generated by Django 5.2.17 on 2026-08-24 17:33

import django.core.validators
import django.db.models.deletion
import tareas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("alumnos", "0001_initial"),
        ("calificaciones", "0001_initial"),
        ("docentes", "0001_initial"),
        ("instituciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntregaTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENTREGADA", "Entregada"),
                            ("ENTREGADA_TARDE", "Entregada tarde"),
                            ("NO_ENTREGADA", "No entregada"),
                        ],
                        default="PENDIENTE",
                        max_length=16,
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                ("calificada", models.BooleanField(default=False)),
                ("observacion_docente", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entregas_tareas",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "entregada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entregas_tareas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entregas_tareas",
                        to="alumnos.inscripcion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entregas_tareas",
                        to="instituciones.institucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdjuntoEntrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=tareas.models.ruta_entrega,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                (
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                )
                            ),
                            tareas.models.validar_archivo_seguro,
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos_entregas",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "entrega",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="tareas.entregatarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=180)),
                ("descripcion", models.TextField(blank=True)),
                ("instrucciones", models.TextField()),
                ("fecha_publicacion", models.DateTimeField()),
                ("fecha_limite", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PUBLICADA", "Publicada"),
                            ("CERRADA", "Cerrada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=10,
                    ),
                ),
                ("permite_entrega_archivo", models.BooleanField(default=False)),
                ("activa", models.BooleanField(default=True)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("motivo_reapertura", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actividad_evaluacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas",
                        to="calificaciones.actividadevaluacion",
                    ),
                ),
                (
                    "anulada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas_anuladas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asignacion_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas",
                        to="docentes.asignaciondocente",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas",
                        to="academico.cursoinstitucion",
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas",
                        to="academico.gradoinstitucion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "reabierta_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tareas_reabiertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tareas",
                        to="academico.seccion",
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_publicacion", "fecha_limite"),
            },
        ),
        migrations.AddField(
            model_name="entregatarea",
            name="tarea",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entregas",
                to="tareas.tarea",
            ),
        ),
        migrations.CreateModel(
            name="AdjuntoTarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=tareas.models.ruta_tarea,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                (
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "ppt",
                                    "pptx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                )
                            ),
                            tareas.models.validar_archivo_seguro,
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("tipo", models.CharField(blank=True, max_length=100)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos_tareas",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "tarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="tareas.tarea",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tarea",
            index=models.Index(
                fields=["institucion", "ciclo"], name="tarea_inst_ciclo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarea",
            index=models.Index(
                fields=["institucion", "estado"], name="tarea_inst_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarea",
            index=models.Index(
                fields=["seccion", "fecha_limite"], name="tarea_secc_limite_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarea",
            index=models.Index(
                fields=["asignacion_docente", "estado"], name="tarea_asig_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entregatarea",
            index=models.Index(
                fields=["tarea", "alumno"], name="entrega_tarea_alumno_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entregatarea",
            constraint=models.UniqueConstraint(
                fields=("tarea", "alumno"), name="entrega_unica_tarea_alumno"
            ),
        ),
    ]
