import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("catalogos", "0001_initial"), ("instituciones", "0001_initial")]
    operations = [
        migrations.CreateModel(name="CicloEscolar", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("nombre", models.CharField(max_length=120)), ("anio", models.PositiveSmallIntegerField()), ("fecha_inicio", models.DateField()), ("fecha_fin", models.DateField()), ("activo", models.BooleanField(default=True)), ("es_actual", models.BooleanField(default=False)), ("cerrado", models.BooleanField(default=False)), ("fecha_creacion", models.DateTimeField(auto_now_add=True)), ("fecha_actualizacion", models.DateTimeField(auto_now=True)), ("institucion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ciclos_escolares", to="instituciones.institucion"))], options={"ordering": ("-anio", "nombre")}),
        migrations.CreateModel(name="JornadaInstitucion", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("codigo", models.CharField(max_length=30)), ("nombre", models.CharField(max_length=100)), ("hora_inicio", models.TimeField(blank=True, null=True)), ("hora_fin", models.TimeField(blank=True, null=True)), ("activa", models.BooleanField(default=True)), ("orden", models.PositiveSmallIntegerField(default=0)), ("institucion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jornadas", to="instituciones.institucion"))], options={"ordering": ("orden", "nombre")}),
        migrations.CreateModel(name="OfertaAcademica", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("nombre_mostrado", models.CharField(max_length=220)), ("codigo_interno", models.CharField(max_length=50)), ("origen", models.CharField(choices=[("CATALOGO", "Catálogo"), ("PERSONALIZADA", "Personalizada")], default="CATALOGO", max_length=20)), ("activa", models.BooleanField(default=True)), ("fecha_creacion", models.DateTimeField(auto_now_add=True)), ("fecha_actualizacion", models.DateTimeField(auto_now=True)), ("carrera_catalogo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ofertas_institucionales", to="catalogos.carreracatalogo")), ("ciclo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ofertas", to="academico.cicloescolar")), ("institucion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ofertas_academicas", to="instituciones.institucion")), ("nivel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ofertas_institucionales", to="catalogos.niveleducativo")), ("version_pensum", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="ofertas_institucionales", to="catalogos.versionpensum"))], options={"ordering": ("nivel__orden", "nombre_mostrado")}),
        migrations.CreateModel(name="GradoInstitucion", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("codigo", models.CharField(max_length=30)), ("nombre", models.CharField(max_length=100)), ("orden", models.PositiveSmallIntegerField(default=0)), ("activo", models.BooleanField(default=True)), ("ciclo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="grados", to="academico.cicloescolar")), ("grado_pensum_origen", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="grados_institucionales", to="catalogos.gradopensum")), ("institucion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grados_institucionales", to="instituciones.institucion")), ("oferta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="grados", to="academico.ofertaacademica"))], options={"ordering": ("orden", "nombre")}),
        migrations.CreateModel(name="CursoInstitucion", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("nombre_mostrado", models.CharField(blank=True, max_length=180)), ("nombre_personalizado", models.CharField(blank=True, max_length=180)), ("periodos_semanales", models.PositiveSmallIntegerField(blank=True, null=True)), ("obligatorio", models.BooleanField(default=True)), ("origen", models.CharField(choices=[("OFICIAL", "Oficial"), ("INSTITUCIONAL", "Institucional")], max_length=20)), ("orden", models.PositiveSmallIntegerField(default=0)), ("activo", models.BooleanField(default=True)), ("ciclo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cursos", to="academico.cicloescolar")), ("curso_catalogo", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cursos_institucionales", to="catalogos.cursocatalogo")), ("curso_pensum_origen", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cursos_institucionales", to="catalogos.cursopensum")), ("grado", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cursos", to="academico.gradoinstitucion")), ("institucion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cursos_institucionales", to="instituciones.institucion")), ("oferta", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cursos", to="academico.ofertaacademica"))], options={"ordering": ("grado__orden", "orden", "nombre_mostrado")}),
        migrations.CreateModel(name="Seccion", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("codigo", models.CharField(max_length=30)), ("nombre", models.CharField(max_length=80)), ("capacidad", models.PositiveSmallIntegerField(blank=True, null=True)), ("activa", models.BooleanField(default=True)), ("ciclo", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="secciones", to="academico.cicloescolar")), ("grado", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="secciones", to="academico.gradoinstitucion")), ("institucion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="secciones", to="instituciones.institucion")), ("jornada", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="secciones", to="academico.jornadainstitucion"))], options={"ordering": ("grado__orden", "jornada__orden", "nombre")}),
        migrations.AddConstraint(model_name="cicloescolar", constraint=models.UniqueConstraint(fields=("institucion", "anio"), name="ciclo_anio_unico_institucion")), migrations.AddConstraint(model_name="cicloescolar", constraint=models.UniqueConstraint(condition=models.Q(("es_actual", True)), fields=("institucion",), name="un_ciclo_actual_institucion")), migrations.AddIndex(model_name="cicloescolar", index=models.Index(fields=["institucion", "activo"], name="ciclo_inst_activo_idx")),
        migrations.AddConstraint(model_name="jornadainstitucion", constraint=models.UniqueConstraint(fields=("institucion", "codigo"), name="jornada_codigo_unico_institucion")), migrations.AddIndex(model_name="jornadainstitucion", index=models.Index(fields=["institucion", "activa"], name="jornada_inst_activa_idx")),
        migrations.AddConstraint(model_name="ofertaacademica", constraint=models.UniqueConstraint(fields=("institucion", "ciclo", "codigo_interno"), name="oferta_codigo_unico_ciclo")), migrations.AddConstraint(model_name="ofertaacademica", constraint=models.UniqueConstraint(condition=models.Q(("version_pensum__isnull", False)), fields=("institucion", "ciclo", "carrera_catalogo", "version_pensum"), name="oferta_pensum_unico_institucion")), migrations.AddIndex(model_name="ofertaacademica", index=models.Index(fields=["institucion", "ciclo", "activa"], name="oferta_inst_ciclo_idx")),
        migrations.AddConstraint(model_name="gradoinstitucion", constraint=models.UniqueConstraint(fields=("oferta", "codigo"), name="grado_codigo_unico_oferta")), migrations.AddIndex(model_name="gradoinstitucion", index=models.Index(fields=["institucion", "ciclo", "activo"], name="grado_inst_ciclo_idx")),
        migrations.AddConstraint(model_name="cursoinstitucion", constraint=models.UniqueConstraint(condition=models.Q(("curso_catalogo__isnull", False)), fields=("grado", "curso_catalogo"), name="curso_catalogo_unico_grado_inst")), migrations.AddConstraint(model_name="cursoinstitucion", constraint=models.CheckConstraint(condition=models.Q(models.Q(("curso_catalogo__isnull", False), ("origen", "OFICIAL")), models.Q(("nombre_personalizado__gt", ""), ("origen", "INSTITUCIONAL")), _connector="OR"), name="curso_inst_origen_valido")), migrations.AddIndex(model_name="cursoinstitucion", index=models.Index(fields=["institucion", "ciclo", "activo"], name="curso_inst_ciclo_idx")),
        migrations.AddConstraint(model_name="seccion", constraint=models.UniqueConstraint(condition=models.Q(("jornada__isnull", False)), fields=("grado", "jornada", "nombre"), name="seccion_unica_grado_jornada")), migrations.AddConstraint(model_name="seccion", constraint=models.UniqueConstraint(condition=models.Q(("jornada__isnull", True)), fields=("grado", "nombre"), name="seccion_unica_grado_sin_jornada")), migrations.AddIndex(model_name="seccion", index=models.Index(fields=["institucion", "ciclo", "activa"], name="seccion_inst_ciclo_idx")),
    ]
