# Generated by Django 5.2.17 on 2026-08-27 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0001_initial"),
        ("alumnos", "0002_alumno_usuario_encargado_usuario"),
        ("instituciones", "0003_onboardinginstitucion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cicloescolar",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PLANIFICACION", "Planificación"),
                    ("ACTIVO", "Activo"),
                    ("EN_CIERRE", "En cierre"),
                    ("CERRADO", "Cerrado"),
                ],
                default="PLANIFICACION",
                max_length=14,
            ),
        ),
        migrations.CreateModel(
            name="ResultadoAnualAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promedio_final",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "resultado_sugerido",
                    models.CharField(
                        choices=[
                            ("PROMOVIDO", "Promovido"),
                            ("NO_PROMOVIDO", "No promovido"),
                            ("RETIRADO", "Retirado"),
                            ("TRASLADADO", "Trasladado"),
                            ("PENDIENTE", "Pendiente"),
                            ("NO_APLICA", "No aplica"),
                            ("EGRESADO", "Egresado"),
                        ],
                        default="PENDIENTE",
                        max_length=14,
                    ),
                ),
                (
                    "resultado_final",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PROMOVIDO", "Promovido"),
                            ("NO_PROMOVIDO", "No promovido"),
                            ("RETIRADO", "Retirado"),
                            ("TRASLADADO", "Trasladado"),
                            ("PENDIENTE", "Pendiente"),
                            ("NO_APLICA", "No aplica"),
                            ("EGRESADO", "Egresado"),
                        ],
                        max_length=14,
                        null=True,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("generado_automaticamente", models.BooleanField(default=True)),
                ("fecha_confirmacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_anuales",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados_anuales",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "confirmado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resultados_anuales_confirmados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultado_anual",
                        to="alumnos.inscripcion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_anuales",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ("ciclo__anio", "alumno__primer_apellido"),
                "indexes": [
                    models.Index(
                        fields=["institucion", "ciclo", "resultado_final"],
                        name="resultado_anual_filtro_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("institucion", "ciclo", "alumno"),
                        name="resultado_anual_unico_alumno_ciclo",
                    )
                ],
            },
        ),
    ]
