"""Matriz central de roles institucionales de AulaPro.

Los servicios de dominio pueden definir restricciones adicionales (por ejemplo,
un docente únicamente sobre sus asignaciones), pero nunca ampliar estos grupos.
"""
SUPERADMIN="SUPERADMIN"
PROPIETARIO="PROPIETARIO";DIRECTOR="DIRECTOR";ADMINISTRADOR="ADMINISTRADOR";SECRETARIA="SECRETARIA";CONTABILIDAD="CONTABILIDAD";DOCENTE="DOCENTE";PADRE="PADRE";ALUMNO="ALUMNO"
GESTION_INSTITUCIONAL={PROPIETARIO,DIRECTOR,ADMINISTRADOR}
GESTION_ACADEMICA=GESTION_INSTITUCIONAL
LECTURA_ACADEMICA=GESTION_ACADEMICA|{SECRETARIA,DOCENTE}
GESTION_ALUMNOS=GESTION_INSTITUCIONAL|{SECRETARIA}
LECTURA_FINANCIERA=GESTION_INSTITUCIONAL|{SECRETARIA,CONTABILIDAD}
GESTION_FINANCIERA=GESTION_INSTITUCIONAL|{CONTABILIDAD,SECRETARIA}
GESTION_COMUNICACIONES=GESTION_INSTITUCIONAL|{SECRETARIA}
ROLES_PORTAL={PADRE,ALUMNO}
TODOS_INSTITUCIONALES={PROPIETARIO,DIRECTOR,ADMINISTRADOR,SECRETARIA,CONTABILIDAD,DOCENTE,PADRE,ALUMNO}
def rol_actual(request):return getattr(getattr(request,"asignacion_institucion",None),"rol",None)
def tiene_rol(request,roles):return rol_actual(request) in roles
