# Generated by Django 5.2.17 on 2026-08-24 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("alumnos", "0001_initial"),
        ("docentes", "0001_initial"),
        ("instituciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SesionAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("GENERAL", "General"), ("CURSO", "Por curso")],
                        max_length=10,
                    ),
                ),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ABIERTA", "Abierta"),
                            ("CERRADA", "Cerrada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="ABIERTA",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("motivo_reapertura", models.TextField(blank=True)),
                ("fecha_reapertura", models.DateTimeField(blank=True, null=True)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                (
                    "anulada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesiones_asistencia_anuladas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asignacion_docente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_asistencia",
                        to="docentes.asignaciondocente",
                    ),
                ),
                (
                    "cerrada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesiones_asistencia_cerradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_asistencia",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesiones_asistencia_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_asistencia",
                        to="academico.cursoinstitucion",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_asistencia",
                        to="docentes.docente",
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_asistencia",
                        to="academico.gradoinstitucion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones_asistencia",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "oferta_academica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_asistencia",
                        to="academico.ofertaacademica",
                    ),
                ),
                (
                    "reabierta_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sesiones_asistencia_reabiertas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_asistencia",
                        to="academico.seccion",
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha", "grado__orden", "seccion__nombre"),
            },
        ),
        migrations.CreateModel(
            name="RegistroAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SIN_MARCAR", "Sin marcar"),
                            ("PRESENTE", "Presente"),
                            ("AUSENTE", "Ausente"),
                            ("TARDE", "Tarde"),
                        ],
                        default="SIN_MARCAR",
                        max_length=12,
                    ),
                ),
                ("hora_registro", models.TimeField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True)),
                ("justificada", models.BooleanField(default=False)),
                ("motivo_justificacion", models.TextField(blank=True)),
                ("fecha_justificacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_asistencia",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_asistencia",
                        to="alumnos.inscripcion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_asistencia",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "justificada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ausencias_justificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_asistencia_realizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="asistencia.sesionasistencia",
                    ),
                ),
            ],
            options={
                "ordering": ("alumno__primer_apellido", "alumno__primer_nombre"),
            },
        ),
        migrations.AddIndex(
            model_name="sesionasistencia",
            index=models.Index(
                fields=["institucion", "fecha"], name="asist_inst_fecha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sesionasistencia",
            index=models.Index(
                fields=["institucion", "ciclo"], name="asist_inst_ciclo_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sesionasistencia",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("tipo", "GENERAL"), models.Q(("estado", "ANULADA"), _negated=True)
                ),
                fields=("institucion", "fecha", "seccion"),
                name="asistencia_general_unica_activa",
            ),
        ),
        migrations.AddConstraint(
            model_name="sesionasistencia",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("tipo", "CURSO"), models.Q(("estado", "ANULADA"), _negated=True)
                ),
                fields=("institucion", "fecha", "seccion", "curso"),
                name="asistencia_curso_unica_activa",
            ),
        ),
        migrations.AddIndex(
            model_name="registroasistencia",
            index=models.Index(
                fields=["sesion", "estado"], name="registro_sesion_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroasistencia",
            index=models.Index(
                fields=["alumno", "sesion"], name="registro_alumno_sesion_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registroasistencia",
            constraint=models.UniqueConstraint(
                fields=("sesion", "alumno"), name="registro_asistencia_unico_alumno"
            ),
        ),
    ]
