# Generated by Django 5.2.17 on 2026-09-03 20:09

import alumnos.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import rrhh.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("docentes", "0001_initial"),
        ("instituciones", "0003_onboardinginstitucion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas_laborales",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=160)),
                ("apellidos", models.CharField(max_length=160)),
                (
                    "cui",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{13}$",
                                "El CUI debe contener exactamente 13 dígitos.",
                            )
                        ],
                    ),
                ),
                (
                    "dpi",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{13}$",
                                "El CUI debe contener exactamente 13 dígitos.",
                            )
                        ],
                    ),
                ),
                ("nit", models.CharField(blank=True, max_length=20)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Femenino"), ("M", "Masculino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("codigo_empleado", models.CharField(blank=True, max_length=20)),
                ("secuencia", models.PositiveIntegerField(editable=False, null=True)),
                ("fecha_ingreso", models.DateField()),
                ("fecha_egreso", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("SUSPENDIDO", "Suspendido"),
                            ("LICENCIA", "Licencia"),
                            ("INACTIVO", "Inactivo"),
                            ("RETIRADO", "Retirado"),
                        ],
                        default="ACTIVO",
                        max_length=12,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        upload_to="rrhh/fotos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="rrhh.arealaboral",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleados_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "docente",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleado",
                        to="docentes.docente",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleados",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleado",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("apellidos", "nombres"),
                "permissions": [("ver_datos_salariales", "Puede ver datos salariales")],
            },
        ),
        migrations.AddField(
            model_name="arealaboral",
            name="responsable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="areas_responsable",
                to="rrhh.empleado",
            ),
        ),
        migrations.CreateModel(
            name="PermisoLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PERSONAL", "Personal"),
                            ("MEDICO", "Médico"),
                            ("VACACIONES", "Vacaciones"),
                            ("LICENCIA", "Licencia"),
                            ("CITA", "Cita"),
                            ("ESTUDIO", "Estudio"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=12,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("motivo", models.TextField()),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                ("fecha_resolucion", models.DateTimeField(blank=True, null=True)),
                (
                    "autorizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permisos_autorizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permisos",
                        to="rrhh.empleado",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permisos_laborales",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permisos_solicitados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PuestoLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=140)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DIRECTIVO", "Directivo"),
                            ("ADMINISTRATIVO", "Administrativo"),
                            ("DOCENTE", "Docente"),
                            ("OPERATIVO", "Operativo"),
                            ("OTRO", "Otro"),
                        ],
                        default="ADMINISTRATIVO",
                        max_length=16,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="puestos",
                        to="rrhh.arealaboral",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puestos_laborales",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ("area__orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="MovimientoLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INGRESO", "Ingreso"),
                            ("CAMBIO_PUESTO", "Cambio de puesto"),
                            ("CAMBIO_AREA", "Cambio de área"),
                            ("RENOVACION", "Renovación"),
                            ("LICENCIA", "Licencia"),
                            ("REINTEGRO", "Reintegro"),
                            ("EGRESO", "Egreso"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "area_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_origen",
                        to="rrhh.arealaboral",
                    ),
                ),
                (
                    "area_nueva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_destino",
                        to="rrhh.arealaboral",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="rrhh.empleado",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "puesto_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_origen",
                        to="rrhh.puestolaboral",
                    ),
                ),
                (
                    "puesto_nuevo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos_destino",
                        to="rrhh.puestolaboral",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empleado",
            name="puesto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="empleados",
                to="rrhh.puestolaboral",
            ),
        ),
        migrations.CreateModel(
            name="ContratoLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_contrato", models.CharField(max_length=50)),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("INDEFINIDO", "Indefinido"),
                            ("PLAZO_FIJO", "Plazo fijo"),
                            ("SERVICIOS", "Servicios"),
                            ("TEMPORAL", "Temporal"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("jornada_laboral", models.CharField(blank=True, max_length=100)),
                (
                    "salario_referencia",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("VIGENTE", "Vigente"),
                            ("VENCIDO", "Vencido"),
                            ("FINALIZADO", "Finalizado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("motivo_finalizacion", models.TextField(blank=True)),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        upload_to=rrhh.models.ruta_contrato,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("pdf", "jpg", "jpeg", "png", "webp")
                            ),
                            alumnos.models.validar_documento_alumno,
                        ],
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos_laborales",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos",
                        to="rrhh.empleado",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrhh.puestolaboral",
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_inicio",),
            },
        ),
        migrations.CreateModel(
            name="TipoDocumentoEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=140)),
                ("descripcion", models.TextField(blank=True)),
                ("obligatorio", models.BooleanField(default=True)),
                ("requiere_vigencia", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrhh.arealaboral",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrhh.puestolaboral",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        upload_to=rrhh.models.ruta_documento,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("pdf", "jpg", "jpeg", "png", "webp")
                            ),
                            alumnos.models.validar_documento_alumno,
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(blank=True, max_length=255)),
                ("fecha_emision", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ENTREGADO", "Entregado"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("NO_APLICA", "No aplica"),
                        ],
                        default="ENTREGADO",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "cargado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_empleado_cargados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_empleado_revisados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="rrhh.empleado",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrhh.tipodocumentoempleado",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="arealaboral",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="rrhh_area_codigo_inst"
            ),
        ),
        migrations.AddIndex(
            model_name="permisolaboral",
            index=models.Index(
                fields=["institucion", "estado", "fecha_inicio"],
                name="rrhh_permiso_estado",
            ),
        ),
        migrations.AddConstraint(
            model_name="puestolaboral",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="rrhh_puesto_codigo_inst"
            ),
        ),
        migrations.AddIndex(
            model_name="empleado",
            index=models.Index(
                fields=["institucion", "estado"], name="rrhh_emp_inst_estado"
            ),
        ),
        migrations.AddConstraint(
            model_name="empleado",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo_empleado"),
                name="rrhh_empleado_codigo_inst",
            ),
        ),
        migrations.AddConstraint(
            model_name="empleado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cui__isnull", False)),
                fields=("institucion", "cui"),
                name="rrhh_empleado_cui_inst",
            ),
        ),
        migrations.AddConstraint(
            model_name="empleado",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dpi__isnull", False)),
                fields=("institucion", "dpi"),
                name="rrhh_empleado_dpi_inst",
            ),
        ),
        migrations.AddIndex(
            model_name="contratolaboral",
            index=models.Index(
                fields=["institucion", "estado", "fecha_fin"],
                name="rrhh_contrato_vence",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratolaboral",
            constraint=models.UniqueConstraint(
                fields=("institucion", "numero_contrato"),
                name="rrhh_contrato_numero_inst",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipodocumentoempleado",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="rrhh_tipo_doc_codigo"
            ),
        ),
    ]
