# Generated by Django 5.2.17 on 2026-08-24 21:15

import comunicaciones.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("instituciones", "0002_alter_usuarioinstitucion_rol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comunicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("contenido", models.TextField()),
                ("resumen", models.CharField(blank=True, max_length=280)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ANUNCIO", "Anuncio"),
                            ("CIRCULAR", "Circular"),
                            ("AVISO", "Aviso"),
                            ("RECORDATORIO", "Recordatorio"),
                        ],
                        default="AVISO",
                        max_length=15,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("IMPORTANTE", "Importante"),
                            ("URGENTE", "Urgente"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("PROGRAMADA", "Programada"),
                            ("PUBLICADA", "Publicada"),
                            ("ARCHIVADA", "Archivada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                    ),
                ),
                (
                    "fecha_publicacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "anulada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comunicaciones_anuladas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comunicaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comunicaciones",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "publicada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comunicaciones_publicadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_publicacion",),
            },
        ),
        migrations.CreateModel(
            name="AdjuntoComunicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=comunicaciones.models.ruta_adjunto,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                (
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                )
                            ),
                            comunicaciones.models.validar_adjunto,
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos_comunicaciones",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "comunicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="comunicaciones.comunicacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComunicacionAudiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rol", models.CharField(max_length=20)),
                (
                    "comunicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiencias",
                        to="comunicaciones.comunicacion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComunicacionDestino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_destino",
                    models.CharField(
                        choices=[
                            ("INSTITUCION", "Toda la institución"),
                            ("ROL", "Rol"),
                            ("GRADO", "Grado"),
                            ("SECCION", "Sección"),
                            ("CURSO", "Curso"),
                            ("USUARIO", "Usuario"),
                        ],
                        max_length=12,
                    ),
                ),
                ("rol", models.CharField(blank=True, max_length=20)),
                (
                    "ciclo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "comunicacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinos",
                        to="comunicaciones.comunicacion",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.cursoinstitucion",
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.gradoinstitucion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinos_comunicaciones",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.seccion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.CharField(blank=True, max_length=400)),
                (
                    "tipo_origen",
                    models.CharField(default="COMUNICACION", max_length=30),
                ),
                ("origen_id", models.CharField(blank=True, max_length=80)),
                ("url_destino", models.CharField(blank=True, max_length=500)),
                ("leida", models.BooleanField(default=False)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "comunicacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="comunicaciones.comunicacion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_creacion",),
            },
        ),
        migrations.AddIndex(
            model_name="comunicacion",
            index=models.Index(
                fields=["institucion", "estado"], name="com_inst_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comunicacion",
            index=models.Index(
                fields=["institucion", "fecha_publicacion"], name="com_inst_public_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="comunicacionaudiencia",
            constraint=models.UniqueConstraint(
                fields=("comunicacion", "rol"), name="com_audiencia_unica"
            ),
        ),
        migrations.AddIndex(
            model_name="notificacion",
            index=models.Index(
                fields=["usuario", "leida"], name="notif_usuario_leida_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="notificacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("comunicacion__isnull", False)),
                fields=("comunicacion", "usuario"),
                name="notif_com_usuario_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="notificacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("origen_id", ""), _negated=True),
                fields=("institucion", "usuario", "tipo_origen", "origen_id"),
                name="notif_origen_usuario_unica",
            ),
        ),
    ]
