# Generated by Django 5.2.17 on 2026-09-03 19:00

import admisiones.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_cicloescolar_estado_resultadoanualalumno"),
        ("instituciones", "0003_onboardinginstitucion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aspirante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=160)),
                ("apellidos", models.CharField(max_length=160)),
                (
                    "cui",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{13}$",
                                "El CUI debe contener exactamente 13 dígitos.",
                            )
                        ],
                    ),
                ),
                ("fecha_nacimiento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Femenino"), ("M", "Masculino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("colegio_anterior", models.CharField(blank=True, max_length=180)),
                ("ultimo_grado_cursado", models.CharField(blank=True, max_length=120)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROSPECTO", "Prospecto"),
                            ("EN_PROCESO", "En proceso"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("LISTA_ESPERA", "Lista de espera"),
                            ("INSCRITO", "Inscrito"),
                            ("RETIRADO", "Retirado"),
                        ],
                        default="PROSPECTO",
                        max_length=15,
                    ),
                ),
                ("posible_duplicado", models.BooleanField(default=False)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspirantes",
                        to="instituciones.institucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConfiguracionAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admisiones_abiertas", models.BooleanField(default=False)),
                (
                    "titulo_publico",
                    models.CharField(default="Proceso de admisión", max_length=180),
                ),
                ("mensaje_publico", models.TextField(blank=True)),
                ("requiere_cui", models.BooleanField(default=False)),
                ("permitir_carga_documentos", models.BooleanField(default=True)),
                (
                    "requiere_documentos_completos_para_aprobar",
                    models.BooleanField(default=False),
                ),
                ("correo_contacto", models.EmailField(blank=True, max_length=254)),
                ("telefono_contacto", models.CharField(blank=True, max_length=30)),
                (
                    "ciclo_predeterminado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "institucion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_admision",
                        to="instituciones.institucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EncargadoAspirante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=160)),
                ("apellidos", models.CharField(blank=True, max_length=160)),
                ("parentesco", models.CharField(default="PADRE", max_length=30)),
                ("telefono", models.CharField(max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("dpi", models.CharField(blank=True, max_length=13)),
                ("es_principal", models.BooleanField(default=True)),
                (
                    "aspirante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encargados",
                        to="admisiones.aspirante",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_solicitud", models.CharField(blank=True, max_length=24)),
                ("secuencia", models.PositiveIntegerField(editable=False, null=True)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "fecha_solicitud",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("NUEVA", "Nueva"),
                            ("EN_REVISION", "En revisión"),
                            ("DOCUMENTACION_PENDIENTE", "Documentación pendiente"),
                            ("ENTREVISTA_PENDIENTE", "Entrevista pendiente"),
                            ("EVALUACION_PENDIENTE", "Evaluación pendiente"),
                            ("EN_DECISION", "En decisión"),
                            ("APROBADA", "Aprobada"),
                            ("LISTA_ESPERA", "Lista de espera"),
                            ("RECHAZADA", "Rechazada"),
                            ("INSCRITA", "Inscrita"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="NUEVA",
                        max_length=30,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("REFERIDO", "Referido"),
                            ("REDES_SOCIALES", "Redes sociales"),
                            ("PAGINA_WEB", "Página web"),
                            ("PUBLICIDAD", "Publicidad"),
                            ("VISITA", "Visita"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("posicion_espera", models.PositiveIntegerField(blank=True, null=True)),
                ("fecha_lista_espera", models.DateField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "aspirante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="admisiones.aspirante",
                    ),
                ),
                (
                    "ciclo_solicitado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grado_solicitado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.gradoinstitucion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_admision",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "jornada_solicitada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.jornadainstitucion",
                    ),
                ),
                (
                    "oferta_solicitada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.ofertaacademica",
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_solicitud",),
            },
        ),
        migrations.CreateModel(
            name="EntrevistaAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_programada", models.DateTimeField()),
                ("fecha_realizada", models.DateTimeField(blank=True, null=True)),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("PRESENCIAL", "Presencial"),
                            ("VIRTUAL", "Virtual"),
                            ("TELEFONICA", "Telefónica"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PROGRAMADA", "Programada"),
                            ("REALIZADA", "Realizada"),
                            ("REPROGRAMADA", "Reprogramada"),
                            ("CANCELADA", "Cancelada"),
                            ("NO_ASISTIO", "No asistió"),
                        ],
                        default="PROGRAMADA",
                        max_length=15,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "recomendacion",
                    models.CharField(
                        choices=[
                            ("FAVORABLE", "Favorable"),
                            (
                                "FAVORABLE_CON_OBSERVACIONES",
                                "Favorable con observaciones",
                            ),
                            ("NO_FAVORABLE", "No favorable"),
                            ("PENDIENTE", "Pendiente"),
                        ],
                        default="PENDIENTE",
                        max_length=35,
                    ),
                ),
                (
                    "entrevistador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entrevistas",
                        to="admisiones.solicitudadmision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoDocumentoAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=140)),
                ("obligatorio", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=admisiones.models.ruta,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("pdf", "jpg", "jpeg", "png", "webp")
                            ),
                            admisiones.models.validar_archivo,
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ENTREGADO", "Entregado"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                        ],
                        default="ENTREGADO",
                        max_length=12,
                    ),
                ),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="admisiones.solicitudadmision",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admisiones.tipodocumentoadmision",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoEvaluacionAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=140)),
                ("descripcion", models.TextField(blank=True)),
                ("punteo_maximo", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "punteo_minimo_referencia",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluacionAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "punteo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("REALIZADA", "Realizada"),
                            ("ANULADA", "Anulada"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                (
                    "evaluado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evaluaciones_admision_asignadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="admisiones.solicitudadmision",
                    ),
                ),
                (
                    "tipo_evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admisiones.tipoevaluacionadmision",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aspirante",
            index=models.Index(
                fields=["institucion", "estado"], name="asp_inst_estado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="solicitudadmision",
            index=models.Index(
                fields=["institucion", "estado"], name="sol_inst_estado_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitudadmision",
            constraint=models.UniqueConstraint(
                fields=("institucion", "numero_solicitud"), name="sol_numero_unico_inst"
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitudadmision",
            constraint=models.UniqueConstraint(
                fields=("institucion", "ciclo_solicitado", "secuencia"),
                name="sol_secuencia_unica",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipodocumentoadmision",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="tipo_doc_adm_unico"
            ),
        ),
    ]
