import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations,models

class Migration(migrations.Migration):
 initial=True
 dependencies=[("academico","0001_initial"),("instituciones","0001_initial"),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
 operations=[
  migrations.CreateModel(name="Familia",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("codigo",models.CharField(blank=True,max_length=20,null=True)),("nombre_referencia",models.CharField(max_length=180)),("direccion",models.TextField(blank=True)),("telefono_principal",models.CharField(blank=True,max_length=30)),("email_principal",models.EmailField(blank=True,max_length=254)),("observaciones",models.TextField(blank=True)),("activa",models.BooleanField(default=True)),("fecha_creacion",models.DateTimeField(auto_now_add=True)),("fecha_actualizacion",models.DateTimeField(auto_now=True)),("institucion",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="familias",to="instituciones.institucion"))],options={"ordering":("nombre_referencia",)}),
  migrations.CreateModel(name="Alumno",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("cui",models.CharField(blank=True,max_length=13,null=True,validators=[django.core.validators.RegexValidator("^\\d{13}$","El CUI debe contener exactamente 13 dígitos.")])),("estado_identificacion",models.CharField(choices=[("VALIDADO","Validado"),("PENDIENTE","Pendiente")],default="PENDIENTE",max_length=12)),("codigo_interno",models.CharField(blank=True,max_length=40)),("primer_nombre",models.CharField(max_length=60)),("segundo_nombre",models.CharField(blank=True,max_length=60)),("otros_nombres",models.CharField(blank=True,max_length=100)),("primer_apellido",models.CharField(max_length=60)),("segundo_apellido",models.CharField(blank=True,max_length=60)),("apellido_casada",models.CharField(blank=True,max_length=60)),("fecha_nacimiento",models.DateField()),("sexo",models.CharField(choices=[("F","Femenino"),("M","Masculino"),("O","Otro / no especificado")],max_length=1)),("telefono",models.CharField(blank=True,max_length=30)),("email",models.EmailField(blank=True,max_length=254)),("direccion",models.TextField(blank=True)),("departamento",models.CharField(blank=True,max_length=80)),("municipio",models.CharField(blank=True,max_length=80)),("fotografia",models.ImageField(blank=True,upload_to="alumnos/fotografias/",validators=[django.core.validators.FileExtensionValidator(["jpg","jpeg","png","webp"])])),("estado",models.CharField(choices=[("ACTIVO","Activo"),("INACTIVO","Inactivo"),("RETIRADO","Retirado"),("EGRESADO","Egresado")],default="ACTIVO",max_length=10)),("fecha_ingreso",models.DateField()),("fecha_creacion",models.DateTimeField(auto_now_add=True)),("fecha_actualizacion",models.DateTimeField(auto_now=True)),("familia",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="alumnos",to="alumnos.familia")),("institucion",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="alumnos",to="instituciones.institucion"))],options={"ordering":("primer_apellido","segundo_apellido","primer_nombre")}),
  migrations.CreateModel(name="Encargado",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("cui",models.CharField(blank=True,max_length=13,null=True,validators=[django.core.validators.RegexValidator("^\\d{13}$","El CUI debe contener exactamente 13 dígitos.")])),("nombres",models.CharField(max_length=160)),("apellidos",models.CharField(max_length=160)),("telefono",models.CharField(max_length=30)),("telefono_secundario",models.CharField(blank=True,max_length=30)),("email",models.EmailField(blank=True,max_length=254)),("direccion",models.TextField(blank=True)),("ocupacion",models.CharField(blank=True,max_length=120)),("activo",models.BooleanField(default=True)),("fecha_creacion",models.DateTimeField(auto_now_add=True)),("fecha_actualizacion",models.DateTimeField(auto_now=True)),("institucion",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="encargados",to="instituciones.institucion"))],options={"ordering":("apellidos","nombres")}),
  migrations.CreateModel(name="AlumnoEncargado",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("parentesco",models.CharField(choices=[("MADRE","Madre"),("PADRE","Padre"),("ABUELO","Abuelo"),("ABUELA","Abuela"),("TUTOR","Tutor"),("HERMANO","Hermano"),("HERMANA","Hermana"),("OTRO","Otro")],max_length=12)),("parentesco_otro",models.CharField(blank=True,max_length=80)),("es_principal",models.BooleanField(default=False)),("es_responsable_financiero",models.BooleanField(default=False)),("es_contacto_emergencia",models.BooleanField(default=False)),("autorizado_recoger",models.BooleanField(default=False)),("convive_con_alumno",models.BooleanField(default=False)),("observaciones",models.TextField(blank=True)),("activo",models.BooleanField(default=True)),("alumno",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="vinculos_encargados",to="alumnos.alumno")),("encargado",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="vinculos_alumnos",to="alumnos.encargado")),("institucion",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="vinculos_encargados",to="instituciones.institucion"))]),
  migrations.CreateModel(name="Inscripcion",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("fecha_inscripcion",models.DateField()),("numero_inscripcion",models.CharField(blank=True,max_length=40)),("estado",models.CharField(choices=[("BORRADOR","Borrador"),("ACTIVA","Activa"),("RETIRADA","Retirada"),("TRASLADADA","Trasladada"),("FINALIZADA","Finalizada"),("ANULADA","Anulada")],default="ACTIVA",max_length=12)),("es_reingreso",models.BooleanField(default=False)),("observaciones",models.TextField(blank=True)),("fecha_retiro",models.DateField(blank=True,null=True)),("motivo_retiro",models.TextField(blank=True)),("fecha_creacion",models.DateTimeField(auto_now_add=True)),("fecha_actualizacion",models.DateTimeField(auto_now=True)),("alumno",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inscripciones",to="alumnos.alumno")),("ciclo",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inscripciones",to="academico.cicloescolar")),("grado",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inscripciones",to="academico.gradoinstitucion")),("institucion",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="inscripciones",to="instituciones.institucion")),("oferta_academica",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inscripciones",to="academico.ofertaacademica")),("seccion",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inscripciones",to="academico.seccion"))],options={"ordering":("-ciclo__anio","alumno__primer_apellido")}),
  migrations.CreateModel(name="ImportacionAlumnos",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("archivo_original",models.FileField(blank=True,upload_to="alumnos/importaciones/")),("nombre_archivo",models.CharField(max_length=255)),("estado",models.CharField(choices=[("VALIDANDO","Validando"),("LISTA","Lista"),("PROCESADA","Procesada"),("FALLIDA","Fallida")],default="VALIDANDO",max_length=12)),("total_filas",models.PositiveIntegerField(default=0)),("creados",models.PositiveIntegerField(default=0)),("actualizados",models.PositiveIntegerField(default=0)),("inscripciones_creadas",models.PositiveIntegerField(default=0)),("errores",models.PositiveIntegerField(default=0)),("detalle_errores",models.JSONField(blank=True,default=list)),("fecha_inicio",models.DateTimeField(auto_now_add=True)),("fecha_fin",models.DateTimeField(blank=True,null=True)),("ciclo",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="importaciones_alumnos",to="academico.cicloescolar")),("institucion",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="importaciones_alumnos",to="instituciones.institucion")),("usuario",models.ForeignKey(null=True,on_delete=django.db.models.deletion.SET_NULL,related_name="importaciones_alumnos",to=settings.AUTH_USER_MODEL))],options={"ordering":("-fecha_inicio",)}),
  migrations.AddConstraint(model_name="familia",constraint=models.UniqueConstraint(condition=models.Q(("codigo__isnull",False)),fields=("institucion","codigo"),name="familia_codigo_unico_institucion")),migrations.AddIndex(model_name="familia",index=models.Index(fields=["institucion","activa"],name="familia_inst_activa_idx")),
  migrations.AddConstraint(model_name="alumno",constraint=models.UniqueConstraint(condition=models.Q(("cui__isnull",False)),fields=("institucion","cui"),name="alumno_cui_unico_institucion")),migrations.AddIndex(model_name="alumno",index=models.Index(fields=["institucion","estado"],name="alumno_inst_estado_idx")),migrations.AddIndex(model_name="alumno",index=models.Index(fields=["institucion","primer_apellido","primer_nombre"],name="alumno_nombre_idx")),
  migrations.AddConstraint(model_name="encargado",constraint=models.UniqueConstraint(condition=models.Q(("cui__isnull",False)),fields=("institucion","cui"),name="encargado_cui_unico_institucion")),migrations.AddIndex(model_name="encargado",index=models.Index(fields=["institucion","activo"],name="encargado_inst_activo_idx")),
  migrations.AddConstraint(model_name="alumnoencargado",constraint=models.UniqueConstraint(fields=("alumno","encargado"),name="alumno_encargado_unico")),migrations.AddIndex(model_name="alumnoencargado",index=models.Index(fields=["institucion","activo"],name="vinculo_inst_activo_idx")),
  migrations.AddConstraint(model_name="inscripcion",constraint=models.UniqueConstraint(condition=models.Q(("estado","ACTIVA")),fields=("alumno","ciclo"),name="inscripcion_activa_unica_ciclo")),migrations.AddIndex(model_name="inscripcion",index=models.Index(fields=["institucion","ciclo","estado"],name="inscripcion_inst_ciclo_idx")),migrations.AddIndex(model_name="importacionalumnos",index=models.Index(fields=["institucion","estado"],name="import_inst_estado_idx")),
 ]
