# Generated by Django 5.2.17 on 2026-09-01 20:17

import alumnos.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0002_cicloescolar_estado_resultadoanualalumno"),
        ("alumnos", "0002_alumno_usuario_encargado_usuario"),
        ("catalogos", "0001_initial"),
        ("instituciones", "0003_onboardinginstitucion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumentoAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=140)),
                ("descripcion", models.TextField(blank=True)),
                ("obligatorio", models.BooleanField(default=True)),
                ("requiere_vigencia", models.BooleanField(default=False)),
                ("permite_multiples", models.BooleanField(default=False)),
                ("visible_portal", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_documento_alumno",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="RequisitoDocumentoAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obligatorio", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "aplica_a_ciclo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitos_documentales",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "aplica_a_grado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitos_documentales",
                        to="academico.gradoinstitucion",
                    ),
                ),
                (
                    "aplica_a_nivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitos_documentales",
                        to="catalogos.niveleducativo",
                    ),
                ),
                (
                    "aplica_a_oferta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitos_documentales",
                        to="academico.ofertaacademica",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requisitos_documentales",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitos",
                        to="alumnos.tipodocumentoalumno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ENTREGADO", "Entregado"),
                            ("APROBADO", "Aprobado"),
                            ("RECHAZADO", "Rechazado"),
                            ("VENCIDO", "Vencido"),
                            ("NO_APLICA", "No aplica"),
                        ],
                        default="ENTREGADO",
                        max_length=12,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        upload_to=alumnos.models.ruta_documento_alumno,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("pdf", "jpg", "jpeg", "png", "webp")
                            ),
                            alumnos.models.validar_documento_alumno,
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(blank=True, max_length=255)),
                ("numero_documento", models.CharField(blank=True, max_length=100)),
                ("fecha_emision", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "cargado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_alumno_cargados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos_alumnos",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="alumnos.inscripcion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_alumnos",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "reemplaza_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reemplazos",
                        to="alumnos.documentoalumno",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_alumno_revisados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="alumnos.tipodocumentoalumno",
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_carga",),
            },
        ),
        migrations.AddConstraint(
            model_name="tipodocumentoalumno",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="tipo_doc_codigo_unico_inst"
            ),
        ),
        migrations.AddConstraint(
            model_name="requisitodocumentoalumno",
            constraint=models.UniqueConstraint(
                fields=(
                    "institucion",
                    "tipo_documento",
                    "aplica_a_nivel",
                    "aplica_a_oferta",
                    "aplica_a_grado",
                    "aplica_a_ciclo",
                ),
                name="requisito_doc_alcance_unico",
            ),
        ),
        migrations.AddIndex(
            model_name="documentoalumno",
            index=models.Index(
                fields=["institucion", "alumno", "estado"], name="doc_alumno_estado_idx"
            ),
        ),
    ]
