# Generated by Django 5.2.17 on 2026-08-25 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("instituciones", "0002_alter_usuarioinstitucion_rol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuloSaaS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        choices=[
                            ("ACADEMICO", "Académico"),
                            ("ALUMNOS", "Alumnos"),
                            ("DOCENTES", "Docentes"),
                            ("ASISTENCIA", "Asistencia"),
                            ("CALIFICACIONES", "Calificaciones"),
                            ("TAREAS", "Tareas"),
                            ("FINANZAS", "Finanzas"),
                            ("PORTAL", "Portal familiar"),
                            ("COMUNICACIONES", "Comunicaciones"),
                            ("REPORTES", "Reportes"),
                        ],
                        max_length=24,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.SlugField(max_length=30, unique=True)),
                ("nombre", models.CharField(max_length=80)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio_mensual",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_anual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("max_alumnos", models.PositiveIntegerField(blank=True, null=True)),
                ("max_usuarios", models.PositiveIntegerField(blank=True, null=True)),
                ("max_docentes", models.PositiveIntegerField(blank=True, null=True)),
                ("es_personalizado", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
                ("publico", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="PlanModulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("habilitado", models.BooleanField(default=True)),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="configuracion_planes",
                        to="suscripciones.modulosaas",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_modulos",
                        to="suscripciones.plan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plan",
            name="modulos",
            field=models.ManyToManyField(
                related_name="planes",
                through="suscripciones.PlanModulo",
                to="suscripciones.modulosaas",
            ),
        ),
        migrations.CreateModel(
            name="SolicitudCambioPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensaje", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("fecha_atencion", models.DateTimeField(blank=True, null=True)),
                (
                    "atendida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_plan_atendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_plan",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "plan_actual",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_desde",
                        to="suscripciones.plan",
                    ),
                ),
                (
                    "plan_solicitado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_hacia",
                        to="suscripciones.plan",
                    ),
                ),
                (
                    "solicitada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_plan_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha",),
            },
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PRUEBA", "Prueba"),
                            ("ACTIVA", "Activa"),
                            ("VENCIDA", "Vencida"),
                            ("SUSPENDIDA", "Suspendida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PRUEBA",
                        max_length=12,
                    ),
                ),
                (
                    "modalidad",
                    models.CharField(
                        choices=[
                            ("MENSUAL", "Mensual"),
                            ("ANUAL", "Anual"),
                            ("PERSONALIZADA", "Personalizada"),
                        ],
                        default="MENSUAL",
                        max_length=15,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("periodo_prueba_hasta", models.DateField(blank=True, null=True)),
                ("renovacion_automatica", models.BooleanField(default=False)),
                (
                    "max_alumnos_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_usuarios_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "precio_acordado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notas_internas", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suscripciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suscripciones",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suscripciones",
                        to="suscripciones.plan",
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha_inicio", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="HistorialSuscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=40)),
                ("estado_anterior", models.CharField(blank=True, max_length=12)),
                ("estado_nuevo", models.CharField(blank=True, max_length=12)),
                ("detalles", models.JSONField(blank=True, default=dict)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "realizada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan_anterior",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_origen",
                        to="suscripciones.plan",
                    ),
                ),
                (
                    "plan_nuevo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial_destino",
                        to="suscripciones.plan",
                    ),
                ),
                (
                    "suscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historial",
                        to="suscripciones.suscripcion",
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha",),
            },
        ),
        migrations.AddConstraint(
            model_name="planmodulo",
            constraint=models.UniqueConstraint(
                fields=("plan", "modulo"), name="plan_modulo_unico"
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitudcambioplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "PENDIENTE")),
                fields=("institucion",),
                name="solicitud_plan_pendiente_unica",
            ),
        ),
        migrations.AddIndex(
            model_name="suscripcion",
            index=models.Index(
                fields=["estado", "fecha_fin"], name="sus_estado_fin_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="suscripcion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado__in", ("PRUEBA", "ACTIVA", "SUSPENDIDA"))),
                fields=("institucion",),
                name="suscripcion_actual_unica_institucion",
            ),
        ),
        migrations.AddConstraint(
            model_name="suscripcion",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_fin__gte", models.F("fecha_inicio"))),
                name="suscripcion_fechas_validas",
            ),
        ),
    ]
