# Generated by Django 5.2.17 on 2026-08-25 20:20

from django.db import migrations, models


MODULOS = (
    ("ACADEMICO", "Académico", 1, "Gestión de ciclos, grados, secciones y cursos.", "bi-mortarboard"),
    ("ALUMNOS", "Alumnos", 2, "Expedientes, inscripciones, familias y encargados.", "bi-person-vcard"),
    ("DOCENTES", "Docentes", 3, "Personal docente, asignaciones y carga académica.", "bi-person-workspace"),
    ("ASISTENCIA", "Asistencia", 4, "Control diario y reportes de asistencia.", "bi-calendar-check"),
    ("CALIFICACIONES", "Calificaciones", 5, "Períodos, evaluaciones, notas y boletines.", "bi-card-checklist"),
    ("TAREAS", "Tareas", 6, "Tareas, entregas y seguimiento.", "bi-list-task"),
    ("FINANZAS", "Finanzas", 7, "Cargos, pagos, recibos y estados de cuenta.", "bi-wallet2"),
    ("PORTAL", "Portal familiar", 8, "Acceso seguro para padres y alumnos.", "bi-people"),
    ("COMUNICACIONES", "Comunicaciones", 9, "Avisos y notificaciones institucionales.", "bi-megaphone"),
    ("REPORTES", "Reportes", 10, "Analítica y reportes consolidados.", "bi-bar-chart"),
)


def crear_modulos(apps, schema_editor):
    ModuloSaaS = apps.get_model("suscripciones", "ModuloSaaS")
    for codigo, nombre, orden, descripcion, icono in MODULOS:
        ModuloSaaS.objects.update_or_create(
            codigo=codigo,
            defaults={"nombre": nombre, "orden": orden, "descripcion": descripcion, "icono": icono, "activo": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("suscripciones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modulosaas",
            name="descripcion",
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name="modulosaas",
            name="icono",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.RunPython(crear_modulos, migrations.RunPython.noop),
    ]
