# Generated by Django 5.2.17 on 2026-09-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suscripciones", "0006_horarios_academicos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modulosaas",
            name="codigo",
            field=models.CharField(
                choices=[
                    ("ACADEMICO", "Académico"),
                    ("ALUMNOS", "Alumnos"),
                    ("DOCENTES", "Docentes"),
                    ("ASISTENCIA", "Asistencia"),
                    ("CALIFICACIONES", "Calificaciones"),
                    ("TAREAS", "Tareas"),
                    ("FINANZAS", "Finanzas"),
                    ("PORTAL", "Portal familiar"),
                    ("COMUNICACIONES", "Comunicaciones"),
                    ("REPORTES", "Reportes"),
                    ("EXPEDIENTE", "Expediente digital"),
                    ("HORARIOS", "Horarios académicos"),
                    ("SEGUIMIENTO", "Seguimiento estudiantil"),
                ],
                max_length=24,
                unique=True,
            ),
        ),
    ]
