# Generated by Django 5.2.17 on 2026-09-03 15:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import seguimiento.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_cicloescolar_estado_resultadoanualalumno"),
        ("alumnos", "0003_tipodocumentoalumno_requisitodocumentoalumno_and_more"),
        ("docentes", "0001_initial"),
        ("instituciones", "0003_onboardinginstitucion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("POSITIVO", "Positivo"),
                            ("INCIDENCIA", "Incidencia"),
                            ("ACADEMICO", "Académico"),
                            ("CONVIVENCIA", "Convivencia"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_seguimiento",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="RegistroSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("POSITIVO", "Positivo"),
                            ("INCIDENCIA", "Incidencia"),
                            ("ACADEMICO", "Académico"),
                            ("CONVIVENCIA", "Convivencia"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                ("titulo", models.CharField(max_length=180)),
                ("descripcion", models.TextField()),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("NO_APLICA", "No aplica"),
                            ("BAJA", "Baja"),
                            ("MEDIA", "Media"),
                            ("ALTA", "Alta"),
                            ("CRITICA", "Crítica"),
                        ],
                        default="NO_APLICA",
                        max_length=12,
                    ),
                ),
                (
                    "confidencialidad",
                    models.CharField(
                        choices=[
                            ("INTERNO", "Interno"),
                            ("DOCENTES", "Docentes"),
                            ("PADRES", "Padres"),
                            ("PUBLICABLE_PORTAL", "Publicable en portal"),
                        ],
                        default="INTERNO",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("EN_SEGUIMIENTO", "En seguimiento"),
                            ("RESUELTO", "Resuelto"),
                            ("CERRADO", "Cerrado"),
                            ("ANULADO", "Anulado"),
                        ],
                        default="ABIERTO",
                        max_length=20,
                    ),
                ),
                ("conclusion", models.TextField(blank=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("motivo_anulacion", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_seguimiento",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros",
                        to="seguimiento.categoriaseguimiento",
                    ),
                ),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos_cerrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_seguimiento",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="academico.cursoinstitucion",
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="docentes.docente",
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_seguimiento",
                        to="alumnos.inscripcion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_seguimiento",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seguimientos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha", "-fecha_creacion"),
            },
        ),
        migrations.CreateModel(
            name="NotaSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                ("comentario", models.TextField()),
                ("visible_padre", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="seguimiento.registroseguimiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompromisoSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                (
                    "responsable",
                    models.CharField(
                        choices=[
                            ("ALUMNO", "Alumno"),
                            ("PADRE", "Padre"),
                            ("DOCENTE", "Docente"),
                            ("INSTITUCION", "Institución"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "fecha_compromiso",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("fecha_limite", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CUMPLIDO", "Cumplido"),
                            ("VENCIDO", "Vencido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                ("cumplido_fecha", models.DateField(blank=True, null=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compromisos",
                        to="seguimiento.registroseguimiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdjuntoSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=seguimiento.models.ruta_adjunto,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ("pdf", "jpg", "jpeg", "png")
                            ),
                            seguimiento.models.validar_adjunto,
                        ],
                    ),
                ),
                ("nombre_original", models.CharField(max_length=255)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "cargado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="seguimiento.registroseguimiento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReunionSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("participantes", models.TextField(blank=True)),
                ("motivo", models.TextField()),
                ("acuerdos", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuniones_seguimiento",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encargado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="alumnos.encargado",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "registro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reuniones",
                        to="seguimiento.registroseguimiento",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="categoriaseguimiento",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="seg_categoria_codigo_inst"
            ),
        ),
        migrations.AddIndex(
            model_name="registroseguimiento",
            index=models.Index(
                fields=["institucion", "ciclo", "estado"], name="seg_inst_ciclo_estado"
            ),
        ),
        migrations.AddIndex(
            model_name="registroseguimiento",
            index=models.Index(fields=["alumno", "fecha"], name="seg_alumno_fecha"),
        ),
    ]
