# Generated by Django 5.2.17 on 2026-08-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instituciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuarioinstitucion",
            name="rol",
            field=models.CharField(
                choices=[
                    ("PROPIETARIO", "Propietario"),
                    ("DIRECTOR", "Director"),
                    ("ADMINISTRADOR", "Administrador"),
                    ("SECRETARIA", "Secretaría"),
                    ("CONTABILIDAD", "Contabilidad"),
                    ("DOCENTE", "Docente"),
                    ("PADRE", "Padre / encargado"),
                    ("ALUMNO", "Alumno"),
                ],
                max_length=20,
            ),
        ),
    ]
