# Generated by Django 5.2.17 on 2026-08-25 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instituciones", "0002_alter_usuarioinstitucion_rol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingInstitucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paso_actual", models.PositiveSmallIntegerField(default=1)),
                ("completado", models.BooleanField(default=False)),
                ("omitido", models.BooleanField(default=False)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboardings_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institucion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "verbose_name": "onboarding institucional",
                "verbose_name_plural": "onboardings institucionales",
            },
        ),
    ]
