# Generated by Django 5.2.17 on 2026-09-01 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0002_cicloescolar_estado_resultadoanualalumno"),
        ("docentes", "0001_initial"),
        ("instituciones", "0003_onboardinginstitucion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=40)),
                ("nombre", models.CharField(max_length=120)),
                ("capacidad", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=180)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aulas",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ("codigo", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="BloqueHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("orden", models.PositiveSmallIntegerField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CLASE", "Clase"),
                            ("RECREO", "Recreo"),
                            ("ALMUERZO", "Almuerzo"),
                            ("OTRO", "Otro"),
                        ],
                        default="CLASE",
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques_horario",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "jornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bloques_horario",
                        to="academico.jornadainstitucion",
                    ),
                ),
            ],
            options={
                "ordering": ("jornada__orden", "orden"),
            },
        ),
        migrations.CreateModel(
            name="HorarioClase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("LUNES", "Lunes"),
                            ("MARTES", "Martes"),
                            ("MIERCOLES", "Miércoles"),
                            ("JUEVES", "Jueves"),
                            ("VIERNES", "Viernes"),
                            ("SABADO", "Sábado"),
                            ("DOMINGO", "Domingo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("observaciones", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "asignacion_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horarios_clase",
                        to="docentes.asignaciondocente",
                    ),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horarios_clase",
                        to="horarios.aula",
                    ),
                ),
                (
                    "bloque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horarios_clase",
                        to="horarios.bloquehorario",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horarios_clase",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_clase",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "jornada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horarios_clase",
                        to="academico.jornadainstitucion",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="horarios_clase",
                        to="academico.seccion",
                    ),
                ),
            ],
            options={
                "ordering": ("dia_semana", "bloque__orden"),
            },
        ),
        migrations.AddConstraint(
            model_name="aula",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="aula_codigo_unico_inst"
            ),
        ),
        migrations.AddIndex(
            model_name="bloquehorario",
            index=models.Index(
                fields=["institucion", "jornada", "activo"],
                name="bloque_inst_jornada_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bloquehorario",
            constraint=models.UniqueConstraint(
                fields=("institucion", "jornada", "orden"),
                name="bloque_orden_unico_jornada",
            ),
        ),
        migrations.AddIndex(
            model_name="horarioclase",
            index=models.Index(
                fields=["institucion", "ciclo"], name="horario_inst_ciclo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horarioclase",
            index=models.Index(
                fields=["seccion", "dia_semana"], name="horario_seccion_dia_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horarioclase",
            index=models.Index(
                fields=["asignacion_docente", "dia_semana"], name="horario_asig_dia_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="horarioclase",
            index=models.Index(
                fields=["aula", "dia_semana"], name="horario_aula_dia_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="horarioclase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("activo", True)),
                fields=("seccion", "dia_semana", "bloque"),
                name="horario_seccion_bloque_activo",
            ),
        ),
    ]
