# Generated by Django 5.2.17 on 2026-08-24 16:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academico", "0001_initial"),
        ("alumnos", "0001_initial"),
        ("docentes", "0001_initial"),
        ("instituciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionCalificaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota_minima_aprobacion",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("60.00"), max_digits=5
                    ),
                ),
                ("decimales", models.PositiveSmallIntegerField(default=2)),
                ("mostrar_promedio_acumulado", models.BooleanField(default=False)),
                ("permitir_docente_editar_cerrado", models.BooleanField(default=False)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "institucion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuracion_calificaciones",
                        to="instituciones.institucion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("codigo", models.CharField(max_length=30)),
                ("numero_orden", models.PositiveSmallIntegerField()),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("activo", models.BooleanField(default=True)),
                ("cerrado", models.BooleanField(default=False)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("motivo_reapertura", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodos_cerrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="periodos_academicos",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos_academicos",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "reabierto_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodos_reabiertos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("ciclo__anio", "numero_orden"),
            },
        ),
        migrations.CreateModel(
            name="TipoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=30)),
                ("descripcion", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_evaluacion",
                        to="instituciones.institucion",
                    ),
                ),
            ],
            options={
                "ordering": ("orden", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="ActividadEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=160)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateField()),
                ("fecha_entrega", models.DateField(blank=True, null=True)),
                ("punteo_maximo", models.DecimalField(decimal_places=2, max_digits=7)),
                ("ponderacion", models.DecimalField(decimal_places=2, max_digits=5)),
                ("es_recuperacion", models.BooleanField(default=False)),
                ("activa", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "asignacion_docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_evaluacion",
                        to="docentes.asignaciondocente",
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_evaluacion",
                        to="academico.cicloescolar",
                    ),
                ),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actividades_evaluacion_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_evaluacion",
                        to="academico.cursoinstitucion",
                    ),
                ),
                (
                    "grado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_evaluacion",
                        to="academico.gradoinstitucion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades_evaluacion",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "seccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades_evaluacion",
                        to="academico.seccion",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades",
                        to="calificaciones.periodoacademico",
                    ),
                ),
                (
                    "tipo_evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actividades",
                        to="calificaciones.tipoevaluacion",
                    ),
                ),
            ],
            options={
                "ordering": ("periodo__numero_orden", "fecha", "nombre"),
            },
        ),
        migrations.CreateModel(
            name="Calificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CALIFICADO", "Calificado"),
                            ("AUSENTE", "Ausente"),
                            ("EXENTO", "Exento"),
                        ],
                        default="PENDIENTE",
                        max_length=12,
                    ),
                ),
                (
                    "punteo_obtenido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("observacion", models.TextField(blank=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calificaciones",
                        to="calificaciones.actividadevaluacion",
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calificaciones",
                        to="alumnos.alumno",
                    ),
                ),
                (
                    "inscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calificaciones",
                        to="alumnos.inscripcion",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calificaciones",
                        to="instituciones.institucion",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calificaciones_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["actividad", "alumno"],
                        name="calif_actividad_alumno_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actividad", "alumno"),
                        name="calificacion_unica_actividad_alumno",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="periodoacademico",
            index=models.Index(
                fields=["institucion", "ciclo"], name="periodo_inst_ciclo_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="periodoacademico",
            constraint=models.UniqueConstraint(
                fields=("institucion", "ciclo", "codigo"),
                name="periodo_codigo_unico_ciclo",
            ),
        ),
        migrations.AddConstraint(
            model_name="periodoacademico",
            constraint=models.UniqueConstraint(
                fields=("institucion", "ciclo", "numero_orden"),
                name="periodo_orden_unico_ciclo",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipoevaluacion",
            constraint=models.UniqueConstraint(
                fields=("institucion", "codigo"), name="tipo_eval_codigo_unico_inst"
            ),
        ),
        migrations.AddIndex(
            model_name="actividadevaluacion",
            index=models.Index(
                fields=["institucion", "periodo"], name="actividad_inst_periodo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actividadevaluacion",
            index=models.Index(
                fields=["seccion", "periodo"], name="actividad_secc_periodo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actividadevaluacion",
            index=models.Index(
                fields=["curso", "periodo"], name="actividad_curso_periodo_idx"
            ),
        ),
    ]
