from django.contrib import admin
from .models import Alumno,AlumnoEncargado,DocumentoAlumno,Encargado,Familia,ImportacionAlumnos,Inscripcion,RequisitoDocumentoAlumno,TipoDocumentoAlumno
admin.site.register([Alumno,AlumnoEncargado,Encargado,Familia,ImportacionAlumnos,Inscripcion,TipoDocumentoAlumno,RequisitoDocumentoAlumno,DocumentoAlumno])
